// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xxiczjnpcyehrsqzcifo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4aWN6am5wY3llaHJzcXpjaWZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyMzYwOTQsImV4cCI6MjA5NzgxMjA5NH0.kIsaH2RxG4cN4Dd0D9NIwhlrvmVDJ7bshrCyCswHJ2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});